services:
  - type: web
    name: smartshift-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true

  - type: static
    name: smartshift-frontend
    env: static
    rootDir: frontend
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    autoDeploy: true

